<div class="w-1/5 flex flex-col items-center justify-center m-4">
  <img src="{{image}}" alt="" />
  <div class="flex flex-row w-full items-start justify-between p-4">
    <div class="flex flex-col">
      <h1 class="text-2xl">{{nom}}</h1>
      <p class="text-sm">{{prix}}</p>
    </div>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="12"
      height="16"
      viewBox="0 0 12 16"
      fill="none"
    >
      <path
        d="M10.6021 0H0.707614C0.318882 0 0 0.315845 0 0.707614V15.5493L5.65484 9.89445L11.3097 15.5493V0.707614C11.3097 0.315845 10.9938 0 10.6021 0Z"
        fill="black"
        fill-opacity="0.2"
      />
    </svg>
  </div>
</div>
